### ISSUE TITLE
watering can random crash

### ISSUE THREAD

**Issue by Wireless4024** [Kashdeya/Tiny-Progressions#100] opened 2018-05-06 11:40 UTC
`Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking player
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:195)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:788)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at com.kashdeya.tinyprogressions.items.wateringcan.WateringCanBase.func_77663_a(WateringCanBase.java:85)
	at net.minecraft.item.ItemStack.func_77945_a(ItemStack.java:526)
	at net.minecraft.entity.player.InventoryPlayer.func_70429_k(InventoryPlayer.java:363)
	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:511)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2170)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234)
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	... 5 more`

random crash when hold watering can and shift+right click

**Comment by Jepehal** [comment] 2018-05-13 19:33
> [11:51:02] [main/FATAL]: Reported exception thrown!
> net.minecraft.util.ReportedException: Ticking entity
> 	at net.minecraft.world.World.func_72939_s(World.java:1770) ~[amu.class:?]
> 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1845) ~[bib.class:?]
> 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096) ~[bib.class:?]
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397) [bib.class:?]
> 	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
> 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_60]
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_60]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
> 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_60]
> 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
> 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
> 	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
> 	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
> Caused by: java.lang.NullPointerException
> 	at com.kashdeya.tinyprogressions.items.wateringcan.WateringCanBase.func_77663_a(WateringCanBase.java:85) ~[WateringCanBase.class:?]
> 	at net.minecraft.item.ItemStack.func_77945_a(ItemStack.java:526) ~[aip.class:?]
> 	at net.minecraft.entity.player.InventoryPlayer.func_70429_k(InventoryPlayer.java:363) ~[aec.class:?]
> 	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:511) ~[aed.class:?]
> 	at net.minecraft.client.entity.EntityPlayerSP.func_70636_d(EntityPlayerSP.java:1011) ~[bud.class:?]
> 	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2170) ~[vp.class:?]
> 	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234) ~[aed.class:?]
> 	at net.minecraft.client.entity.EntityPlayerSP.func_70071_h_(EntityPlayerSP.java:181) ~[bud.class:?]
> 	at net.minecraft.world.World.func_72866_a(World.java:1990) ~[amu.class:?]
> 	at net.minecraft.world.World.func_72870_g(World.java:1952) ~[amu.class:?]
> 	at net.minecraft.world.World.func_72939_s(World.java:1756) ~[amu.class:?]
> 	... 18 more
> 
I've been getting a similar crash. I have been using the Peace of Mind modpack, and updated to the latest version before receiving the crash again.

**Comment by SlyyJacob** [comment] 2018-05-22 14:26
Same problem, it crashes every time after a while of watering when shift+right click (the automated watering).

```
java.lang.NullPointerException: Ticking player
	at com.kashdeya.tinyprogressions.items.wateringcan.WateringCanBase.func_77663_a(WateringCanBase.java:85)
	at net.minecraft.item.ItemStack.func_77945_a(ItemStack.java:526)
	at net.minecraft.entity.player.InventoryPlayer.func_70429_k(InventoryPlayer.java:363)
	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:511)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2170)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234)
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)
```

I am no expert but it seems to be connected to the function ItemStack thats controlling the particles?

**Comment by ghost** [comment] 2018-05-23 07:10
Hey all, this is to do with a missing null check for a raycast result that I believe is fixed in our dev environments and will be in the next release; @Kashdeya can confirm

**Comment by SlyyJacob** [comment] 2018-05-23 16:18
@ArclightTW Thanks for the info, would it be possible to add/edit some line in the code easily so that I could fix it for myself for now or is the release pretty soon?

**Comment by JoeSGT** [comment] 2018-06-09 21:35
my players cannot join the server also with this error https://pastebin.com/raw/JGv8QU2E
i am unsure how to reproduce this error

**Comment by GenDeathrow** [comment] 2019-01-29 00:13
I am trying to clear up some bugs here. If anyone can confirm if this has been fixed or is still an issue I would like to know. ty.

**Closed as completed** 2019-02-06 11:07 UTC
